version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - github-actions
    reviewers:
      - devpow112
