documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - .github/CODEOWNERS
      - LICENSE
github-actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*.yml
python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
