name: CI
on:
  workflow_call:
permissions:
  contents: read
jobs:
  check-formatting-markdown:
    name: Check Formatting (Markdown)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Check formatting
        uses: davidanson/markdownlint-cli2-action@v5.1.0
        with:
          globs: '**/*.md'
